version: "3"

tasks:
  run:
    deps: [build]
    dir: build
    cmds:
      - ./main
    silent: true
  build:
    deps: [configure]
    sources:
      - src/**/*.c
    cmds:
      - cmake --build build
  configure:
    sources:
      - CMakeLists.txt
    cmds:
      - cmake -S . -G Ninja -B build
  clean:
    cmds:
      - rm -rf cmake-build-debug build .task
